const datos = {
  // Secciones de La Carta
  secciones: [
    { id: 1, key: "Entradas", nombre: "Entradas" },
    { id: 2, key: "Carnes", nombre: "Carnes" },
    { id: 3, key: "Pescados", nombre: "Pescados" },
    { id: 4, key: "Postres", nombre: "Postres" },
    { id: 5, key: "AperitivosCocteles", nombre: "Aperitivos y Cocteles" },
    { id: 6, key: "BebidasCervezas", nombre: "Bebidas y Cervezas" },
  ],
  // Carta del Restaurante
  carta: {
    Entradas: [
      {
        id: 11,
        key: "101",
        nombre: "Dúo Marino",
        descripcion: "causa de atún y ceviche de pescado.",
        precio: "12.900",
        img: "https://i.ibb.co/XXGMSjy/duomarino.png",
        seccion: "Entradas",
      },
      {
        id: 12,
        key: "101",
        nombre: "Cóctel de camarón",
        descripcion: "servido con palta y salsa golf",
        precio: "11.900",
        img: "https://i.ibb.co/tLhm62V/coctelcamaron.png",
        seccion: "Entradas",
      },
      {
        id: 13,
        key: "101",
        nombre: "Pulpo al Olivo",
        descripcion:
          "laminas de pulpo marinadas en aceite de oliva, servidas con salsa de aceitunas.",
        precio: "13.900",
        img: "https://i.ibb.co/HqPG8Dj/pulpoolivo.png",
        seccion: "Entradas",
      },
      {
        id: 14,
        key: "101",
        nombre: "Papa a La Huancaína",
        descripcion:
          "Papa cocida con salsa de queso, leche y ají amarillo, sin picante.",
        precio: "8.900",
        img: "https://i.ibb.co/GPWvf1V/papahuaicaina.png",
        seccion: "Entradas",
      },
      {
        id: 15,
        key: "101",
        nombre: "Ceviche Mixto",
        descripcion: "Camarón, pulpo, calamar y pescado",
        precio: "12.900",
        img: "https://i.ibb.co/VNF0g3H/cevichemixto.png",
        seccion: "Entradas",
      },
    ],
    Carnes: [
      {
        id: 21,
        nombre: "Filete Rustico",
        key: "101",
        descripcion:
          "Filete y espárrago a la plancha bañado con camarones al ajillo y alcaparra, sobre una cama de puré rústico ( aceite de oliva , sal y un toque de cilantro)",
        precio: "15.900",
        img: "https://i.ibb.co/WzWCyqB/fileterustico.png",
        seccion: "Carnes",
      },
      {
        id: 22,
        nombre: "Tacu Tacu de Filete",
        key: "101",
        descripcion:
          "Porotos mezclados con arroz criollo, crema de ají amarillo y filete a la plancha.",
        precio: "15.900",
        img: "https://i.ibb.co/G0QGX4L/tacutacufilete.png",
        seccion: "Carnes",
      },
      {
        id: 23,
        nombre: "Lomo Saltado",
        key: "101",
        descripcion:
          "Lonjas de filete salteadas con cebolla, tomate, cilantro y papas fritas.",
        precio: "13.500",
        img: "https://i.ibb.co/KFGycy5/lomosaltado.png",
        seccion: "Carnes",
      },
      {
        id: 24,
        nombre: "Saltado Mar y Tierra",
        key: "101",
        descripcion:
          "Filete en trozos, flambeados al pisco con cebolla y tomate, sobre delicioso risotto al azafrán y camarones.",
        precio: "13.500",
        img: "https://i.ibb.co/vwnBkth/saltadomarytierra.png",
        seccion: "Carnes",
      },
      {
        id: 25,
        nombre: "Filete a la Pimienta",
        key: "101",
        descripcion: "A la parrilla bañado con salsa de pimienta.",
        precio: "13.200",
        img: "https://i.ibb.co/F698QYx/filetepimienta.png",
        seccion: "Carnes",
      },
    ],
    Pescados: [
      {
        id: 31,
        nombre: "Pescado en Salsa Tamarindo",
        key: "101",
        descripcion:
          "Frito, con salsa tamarindo, cebollín, pimientos, apio y champiñones.",
        precio: "12.500",
        img: "https://i.ibb.co/QjrS1jJ/pescadotamarindo.png",
        seccion: "Pescados",
      },
      {
        id: 32,
        nombre: "Reineta a la plancha",
        key: "101",
        descripcion: "Reineta a la plancha con agregado",
        precio: "11.900",
        img: "https://i.ibb.co/sRXNF1T/reinetaplancha.png",
        seccion: "Pescados",
      },
      {
        id: 33,
        nombre: "Corvina a la plancha",
        key: "101",
        descripcion: "Corvina a la plancha con agregado",
        precio: "12.900",
        img: "https://i.ibb.co/3p7Myxw/corvinaplancha.png",
        seccion: "Pescados",
      },
      {
        id: 34,
        nombre: "Congrio a la plancha",
        key: "101",
        descripcion: "Congrio a la plancha con agregado",
        precio: "11.900",
        img: "https://i.ibb.co/4TtWwLq/congrioplancha.png",
        seccion: "Pescados",
      },
      {
        id: 35,
        nombre: "Merluza a la plancha",
        key: "101",
        descripcion: "Merluza a la plancha con agregado",
        precio: "10.900",
        img: "https://i.ibb.co/YWh9KSJ/merluzaplancha.png",
        seccion: "Pescados",
      },
    ],
    Postres: [
      {
        id: 41,
        nombre: "Suspiro limeño",
        key: "101",
        descripcion:
          "Típica crema a base de leche y yemas, aromatizada con especias y oporto, servida con merengue.",
        precio: "4.900",
        img: "https://i.ibb.co/fvy2Rh9/suspirolimeno.png",
        seccion: "Postres",
      },
      {
        id: 42,
        nombre: "Tiramisú",
        key: "101",
        descripcion:
          "Torta a base de queso y café, bizcocho bañado con crema chantilly y chocolate amargo.",
        precio: "4.900",
        img: "https://i.ibb.co/v3MLQHf/tiramisu.png",
        seccion: "Postres",
      },
      {
        id: 43,
        nombre: "Cheesecake de Maracuyá",
        key: "101",
        descripcion:
          "Con queso Philladelphia, crema de leche, leche condensada, colapez y vainilla.",
        precio: "4.900",
        img: "https://i.ibb.co/wChkPRD/cheesecakemaracuya.png",
        seccion: "Postres",
      },
      {
        id: 44,
        nombre: "Torta de Tres Leches",
        key: "101",
        descripcion:
          "Suave bizcocho humedecido en una mezcla de leches, bañado con merengue y gratinado.",
        precio: "4.900",
        img: "https://i.ibb.co/rxBCTjc/tortatresleches.png",
        seccion: "Postres",
      },
      {
        id: 45,
        nombre: "Suspiro de Lúcuma",
        key: "101",
        descripcion:
          "Crema de leche, yemas y lúcuma aromatizada con especias y oporto, servida con merengue.",
        precio: "4.900",
        img: "https://i.ibb.co/M75q75B/suspirolucuma.png",
        seccion: "Postres",
      },
    ],
    AperitivosCocteles: [
      {
        id: 51,
        nombre: "Martini Dry",
        key: "101",
        descripcion: "Gin, Vermouth dry",
        precio: "6.100",
        img: "https://i.ibb.co/xgknNnb/martini.png",
        seccion: "AperitivosCocteles",
      },
      {
        id: 52,
        nombre: "Daiquiri",
        key: "101",
        descripcion: "Ron Bacardi Blanco, zumo de limon y jarabe de goma.",
        precio: "1000",
        img: "https://i.ibb.co/WtZprZ9/daikiri.png",
        seccion: "AperitivosCocteles",
      },
      {
        id: 53,
        nombre: "Manhattan",
        key: "101",
        descripcion: "Whiskey ,vermouth rosso y angostura.",
        precio: "1000",
        img: "https://i.ibb.co/hMkq58Z/manhatan.png",
        seccion: "AperitivosCocteles",
      },
      {
        id: 54,
        nombre: "Tom Collins",
        key: "101",
        descripcion: "Gin, limón, Jarabe de goma, soda",
        precio: "1000",
        img: "https://i.ibb.co/Hz1XYjP/tomcollins.png",
        seccion: "AperitivosCocteles",
      },
      {
        id: 55,
        nombre: "Caipirinha de Frutas",
        key: "101",
        descripcion: "Cachaza, limón, frutas y jarabe",
        precio: "1000",
        img: "https://i.ibb.co/9ntLgPX/caipirinha.png",
        seccion: "AperitivosCocteles",
      },
    ],
    BebidasCervezas: [
      {
        id: 61,
        nombre: "Kross",
        key: "101",
        descripcion: "Kross",
        precio: "3.500",
        img: "https://i.ibb.co/xM8qfXR/cerveza-kross.png",
        seccion: "BebidasCervezas",
      },
      {
        id: 62,
        nombre: "Kunstmann Torobayo",
        key: "101",
        descripcion: "(Torobayo / Lager /Bock / Miel / Sin Alcohol)",
        precio: "3.500",
        img: "https://i.ibb.co/sjYZrYF/cerveza-kunstman.png",
        seccion: "BebidasCervezas",
      },
      {
        id: 63,
        nombre: "Corona",
        key: "101",
        descripcion: "Corona",
        precio: "3.500",
        img: "https://i.ibb.co/27JyTV4/cerveza-corona.png",
        seccion: "BebidasCervezas",
      },
      {
        id: 64,
        nombre: "Heineken",
        key: "101",
        descripcion: "Heineken",
        precio: "3.500",
        img: "https://i.ibb.co/88WS6mR/cerveza-heiniken.png",
        seccion: "BebidasCervezas",
      },
      {
        id: 65,
        nombre: "Inca Kola",
        key: "101",
        descripcion: "Bebida gaseosa",
        precio: "2.800",
        img: "https://i.ibb.co/2Yqpvxg/cerveza-incacola.png",
        seccion: "BebidasCervezas",
      },
    ],
  },
};

export default datos;
